# docker-compose test
version: "3.9"

services:
  app:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - db
    
    db:
     image: postgres:15
     environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testdb